### ISSUE TITLE
[REQUEST] Make api-endpoint configureable via env-vars

### ISSUE THREAD

**Issue by benbender** [AlecAivazis/houdini#146]
For many setups it would be great, if the url, which houdini uses, could be configured per environment via env-var/.env-file.

It would make houdini more flexible and suited for bigger projects. It could also render the environment-config optional, as it could be provided with a default if the url is provided via .env... Less steps, less code, less errors :)

**Comment by AlecAivazis** [comment]
Hey @benbender! 

I think i need a little more information to understand this. Do you mean the value in the config file? If so, you also can totally use environment variables to fill that value, you just have to make sure to use the rollup replace plugin to replace that string with something that can execute when the client imports the file. It's also worth clarifying that the value not used by the runtime - only by the command line tool when updating the schema (with `generate -p`). 

You also should be able to use the rollup replace plugin to set the value inside of the generated environment file if that's what you meant. 

Let me know if you need more guidance. You can also always reach out to me on discord if you want to share code privately or anything :)

**Comment by benbender** [comment]
The context, I was thinking about, was simply userfriendliness... It's less a problem of doing it (even if I initially tripped over the sveltekit-way of handling envs...), but more a question of lower the initial setup-costs and entry-barriers while promoting best practices :)

In an ideal world one would only have to install one (meta-)package, add the preprocessor and an env-var and the preprocessor figures out the rest with established defaults (at least in dev-mode)... It would be so cool and another nice sellingpoint for sveltekit and houdini! :)

**Comment by AlecAivazis** [comment]
Hm, I worry that I've gotten a little confused but I think we're talking about something different from your initial question. It sounds like you now understand how to configure the url that the client will hit with an environment variable so I'm going to close this issue.

I agree with you that the world you describe would be ideal - it's a bit tricky given the current capabilities of a svelte preprocessor. They really only can look at a single file at a time. For some features, this is enough. For example, the fragment definitions found in a query composition can be inferred and retrieved by looking at the import statements in a given file. It would be tricky to make sure we don't process the same component twice, or get caught in circular imports but I digress. Unfortunately, some features of houdini (for example, the list operation fragments) only really make sense by considering all of the files in a particular project. As far as I can tell, this is impossible to do with just a pre-processor alone. Finding that line between an understandable mental model and having enough magic to make the framework useful is a constant challenge. 

I think it would be really neat to change the default environment stamped out by `init` to pull the value from the config file. I do like having the explicit `environment.ts` file in order to a clear representation of the moving parts. At least that way the user doesn't have to look up more documentation for defining custom network behavior. I suppose the `init` function could do more to streamline the initial setup such as change an existing `src/routes/__layout.svelte` to set the environment... 🤔
