### ISSUE TITLE
Refetch queries

### ISSUE THREAD

**Issue by AlecAivazis** [AlecAivazis/houdini#57]
Queries sometimes need to be refetched, possibly with new arguments

**Comment by plunkettscott** [comment]
Currently have a use case where I need to manipulate filters on the page and re-run a query with the filters adjusted (from query variables). Is this the use case you are referring to here?

**Comment by AlecAivazis** [comment]
Yep! that's exactly right. Atm, your best bet is to embed as much as you can in the URL filters so you can use page transitions to cause a new query to be fired.

If you feel up for adding this, I don't think many changes are needed. [Here](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/runtime/query.ts#L64) is where the return value from `query` is defined. I'm pretty sure all it would take would be adding the function to this object that fires the query (using `fetchQuery` from the exported runtime) and passes the result to the same `writeData` function in that object to update the cache values and subscriptions for the query.

**Comment by pixelmund** [comment]
I started working on this [here](https://github.com/pixelmund/houdini/tree/refetch-queries).

I have some issues with the houdini build:cmd:main command `sed -i '#!/usr/bin/env node' build/cmd.js`, sed: undefined label. Im on Mac and it seems like mac needs another required argument on sed -i [https://mpdaugherty.wordpress.com/2010/05/27/difference-with-sed-in-place-editing-on-mac-os-x-vs-linux/](https://mpdaugherty.wordpress.com/2010/05/27/difference-with-sed-in-place-editing-on-mac-os-x-vs-linux/)

Otherwise its working pretty well, can u look at this @AlecAivazis and tell me what, or if im missing something in my implementation.

**Comment by pixelmund** [comment]
One thing that came to my mind is: Should we return the result of the fetch `{data, error}` or just void?

**Comment by AlecAivazis** [comment]
Feel free to remove that whole `sed` command from package.json - its not necessary and is left overs from the kit effort that I have been meaning to remove

**Comment by plunkettscott** [comment]
> One thing that came to my mind is: Should we return the result of the fetch `{data, error}` or just void?

I think returning the `data` object might make sense. In cases where you just want differentiate from the _new_ data, I think it makes sense to capture the return value (i.e., data tables where you show X records per page). Of course, this should still update the cache.

**Comment by AlecAivazis** [comment]
I wonder if differentiating new and old data is better done in a reactive statement so that we don't have to complicate houdini's api 🤔

**Comment by plunkettscott** [comment]
That could work. I guess my thought was getting the incremental difference, not storing the previous state before the query.

For example, returning the 25 new records to render the next page without having to calculate the diff of the old and new state. It could still be done with a reactive statement though, so I'm definitely okay with keeping the API slimmer.

**Comment by lamaqdahodwala** [comment]
Any docs for this yet?
