### ISSUE TITLE
Use without Sapper or SvelteKit

### ISSUE THREAD

**Issue by dyedgreen** [AlecAivazis/houdini#67]
From reading the documentation it's not clear if/ how this can be used within a bare Svelte app.

If this is possible, how would one use Houdini without using Sapper (i.e. only having a simple Svelte app). If this is currently not possible, why not (and how could that be changed, e.g. if I wanted to submit a PR)?

**Comment by AlecAivazis** [comment]
At the moment, houdini doesn't work in a bare svelte app because `query` does not actually fire a network request. It assumes that the pre-processor has hoisted the query into a `load` function (`preload` in sapper) and that the component using `query` will be passed the data as a prop from the load function. Also, `query` and the other document functions have internal APIs that are not very ergonomic so there would have to be some work done to make the user's life smoother. For a better understanding of what I mean, you can look at the [fragment tests](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-preprocess/src/transforms/fragment.test.ts#L20-L44). The top of that is what the user writes, the block underneath is what the pre-processor turns it into and shows the actual API for the `fragment` function when its invoked. 

Supporting this would probably be best done by building versions of `query`, `mutation`, `subscription`, and `fragment` that don't make these assumptions. You could still use the artifacts that the compiler generates and the caching mechanism would still work which is what powers the actual APIs (ie things like mutation updates would "just work"). It's definitely doable but not something I have time to prioritize at the moment. If you do want to try to add support for a raw svelte app, I can provide any guidance you need

**Comment by dyedgreen** [comment]
Interesting, so queries are actually all run server side before the components are send to the browser, or am I miss understanding the process? 😅

**Comment by AlecAivazis** [comment]
yes that's correct! At least for the first request that is rendered by the server. From then on, queries fire from the client directly to the API (both Sapper and SvelteKit take care of these details when you define the appropriate loader). 

With that understanding, hopefully I can explain why the API isn't setup like relay's (I also use relay in my react projects). In order to get access to the page variables (so users can do something like pull a filter value from the url) the actual logic for computing the variable needs to exist in the `module` script where the actual network request happens. If the variables were just a static value, this wouldn't be a problem - the preprocessor could just copy the value up to the right script. Unfortunately that's too big of a limitation since a user could put all sorts of madness in that function. That means that the preprocessor would be forced to hoist up any necessary logic to perform the computation. By forcing the user to define their variable function in the `module` context, we can guarantee that anything that the user used to compute their variables is also accessible without any complicated hoisting logic. 

Re the return value - I think a promise is a reasonable response from the various document functions in a bare svelte app as long as it resolves to a store so the user can subscribe to updates.

**Comment by AlecAivazis** [comment]
After poking around with possibilities, I think we can support bare this with the current API. At the very least `query`s inside of non page/layout components have the same constraints as a bare component so the two  should have very similar solutions.

related: #72

**Comment by dyedgreen** [comment]
I think one solution could be to split the query API into `lazyLoadedQuery` and `preloadedQuery` (or just `query`), where the later one is the default to use in page components, defers the arguments into the preload-function, while the lazy loaded version fires on the client side, when the component is rendered (and takes the arguments directly). (iirc that's roughly the story with Relay's API as well)

**Comment by AlecAivazis** [comment]
I'd like to avoid doing that if possible. I think the only thing that's missing from the `query` api to support client-only requests is to add a `loading` field to track the state of the response. I agree that a promise would be a more native solution but I'd like to keep the api surface as small as possible. Also, having two different functions that are constrained by file location means that refactoring components from a page/layout into a common component is not as simple as just moving the file - the user would also have to go update all of the `query`s to `clientQuery` or whatever we call it.

**Comment by dyedgreen** [comment]
What do you think of mirroring relays approach more closely and having a preloaded query that is passed the pre-load value explicitly; and then having a loader that can load a given query from within the sapper/ kit (pre)loader side of things (or potentially another function in the frontend); and potentially having a convenience wrapper that lazy loads things by doing something like `query(…, await preloadQuery(…))`

That would break compatibility with the current api but be more flexible in terms of where the loading can happen.

**Comment by AlecAivazis** [comment]
In some sense that's how `query` works now. The actual function exported from the runtime expects [an object](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-preprocess/src/transforms/query.test.ts#L63-L68) that is created by the preprocessor. 

If we wanted to bring the idea of preloading a query into the core API, I think the best way is to leave `query` the way it is and instead add two new functions to the runtime that do the preloading and and subsequent loading. Even if `query` is just a very thin wrapper over `loadPreloadedQuery` (or whatever we call it), having two functions with distinct names lets the preprocessor handle the details for `query` and keeps the API simple in the most common cases. I want to avoid complicating the API to support "advanced" use cases wherever possible.

I think ideally, the logic for preloading a query should be hidden from the user and the framework should just do the "right thing" whenever possible. I think given that houdini is currently only maintained by a single person, the best way to get to that dream is to lean heavily into kit to handle the router integration. I do understand that supporting this is important to integrate with other routes but advanced users are more likely to be okay with a less-than-perfect API that might be heavily caveated.

**Comment by AlecAivazis** [comment]
@dyedgreen I _think_ I have a working update to support `query` in a non-kit or sapper environment. Mind giving #95 a shot and see if it works for you?

**Comment by AlecAivazis** [comment]
Going to reopen this, @pixelmund had a very good point, a lot of the generated code still assumes things like `$app` and sessions. We'll need to generate a bare svelte adapter that avoid this
