### ISSUE TITLE
Improved type generation, and automatic graphql query/mutation strings

### ISSUE THREAD

**Issue by SorenHolstHansen** [AlecAivazis/houdini#88]
At the moment it feels like there is quite a bit of scaffolding going on. When you create a new mutation/query on the backend, you have to either `npx houdini init` all over, or write the corresponding mutation/query in your schema.gql file and `npx houdini generate`. And then you again have to write the mutation/query template string when you want to call it.

I think it would be great if it worked something like [graphql-code-generator](https://www.graphql-code-generator.com/) (see the live example, and choose "operation types" in the dropdown), where you write your mutation/query in some file, run some generation script, and then you get the types and the gql template string. In other words. In stead of the current schema.gql file, where you write types, I suggest the following:
You have a bunch of files with mutations/queries, that you would otherwise write in your template strings like this file
```graphql
# helloQuery.gql
query Hello($name: String!) {
    hello(name: $name) {
        returnedStuff
    }
}
```
And then you can run generate on all those files, and it would generate the types as it does now, i.e. `import {Hello, Hello$result} from '$houdini'`, but it would then also create a `HelloDocument` like in graphql-code-generator, that is just the template string, and then you would maybe not even need `Hello`. E.g. you would then do
```html
<script lang="ts">
	import { query, graphql, HelloDocument } from '$houdini';

	// Before you had to say query<Hello>, but that gets infered here.
	const { data } = query(HelloDocument);

        // $data is now inferred to be of type Hello$result.

</script>
```
That way you only write the mutation/query one time, and the types are more elegantly generated. Also, it is easier to write your schema.gql file, as you don't have to write all the types explicitly.

**Comment by AlecAivazis** [comment]
Hey @SorenHolstHansen - thanks for opening this up. Let me try to unpack it a bit.
 
One of the key designs in houdini is that related stuff should be colocated with your component. When query documents are split up from their components, users are naturally encouraged to think about their queries being shared in ways that aren't tied to their component hierarchy. In my experience (primarily with Relay) it's very important to keep things compartmentalized. When codebases get large, the constant bouncing back and forth between different files can be tiresome. It  Also, I'm not sure I understand the difference between adding your query body in a separate `.gql` file vs your component body. As long as queries and fragments stay focused  they shouldn't get large enough to warrant the extra file, imo. 

Probably worth mentioning that you can use the `--pull-schema` or just `-p` in order to pull down the most recent schema before generating.  This means that you really only have to ever define the schema on the server as the source of truth, and then use it in your component

**Comment by SorenHolstHansen** [comment]
Cool, I didn't know about the --pull-schema option, definitely makes it a lot nicer.

**Comment by ohmree** [comment]
> Also, I'm not sure I understand the difference between adding your query body in a separate `.gql` file vs your component body. As long as queries and fragments stay focused they shouldn't get large enough to warrant the extra file, imo.

One such difference is syntax highlighting - the graphql snippet in the sample from the readme isn't highlighted for me in emacs with [`web-mode`](https://github.com/fxbois/web-mode) and adding support [would be a pain](https://emacshorrors.com/posts/web-mode.html).

Also I haven't checked this, but if svelte's language tools don't integrate with tsserver plugins such as [`ts-graphql-plugin`](https://github.com/Quramy/ts-graphql-plugin) then intellisense is another issue that would be solved by allowing graphql in separate files.
